name: Build

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux-amd64:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    # cache cargo
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: GTK development librarys
      run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev
    - name: build
      run: cargo build --release --all-features 
    - name: rename output
      run: mv target/release/boop-gtk ./boop-gtk.linux.amd64
    - uses: actions/upload-artifact@v2.1.4
      with:
        name: boop-gtk.linux.amd64
        path: ./boop-gtk.linux.amd64
